# Generated by Django 4.1.7 on 2023-04-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
