# Generated by Django 4.1.7 on 2023-05-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livros',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
