# Generated by Django 4.1.7 on 2023-05-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_emprestimo_devolvido_livros_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='disponivel',
            field=models.IntegerField(),
        ),
    ]
